<?php
	$this->module('application')->renderView('error/404');
?>

<style type="text/css">
	#boxmesageerror{
		width:98%;
		margin:2% auto;
		box-shadow: 0px 0px 5px #999;
		-webkit-box-shadow: 0px 0px 5px #999;
		-moz-box-shadow: 0px 0px 5px #999;

	}
	#boxmesageerror h1{
		background-color: #f5f6f7;
	    border-bottom: 1px solid #e5e5e5;
	    color: #4e5665;
	    font-weight: bold;
	    line-height: 19px;
	    padding: 10px 12px;
	    font-size:15px;
	}
	#boxmesageerror #content{
		padding:10px;
		font-size: 13px;
	}
	.code{
		background-color: #ddd;
		border:1px solid #ccc;
		padding:10px 15px;
		margin: 5px 0px;
		word-break:break-all;
	}
</style>