<!DOCTYPE html>
<html lang="<?php echo $this->layout->lang ?>">
<head>
    <noscript>
        <meta http-equiv="refresh" content="0; URL=<?php echo $this->baseUrl('nojavascript') ?>" />
    </noscript>
    <?php $this->title() ?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

   
     <!-- jQuery -->
    <script src="<?php echo $this->asset() ?>js/jquery.js"></script>
    <?php $this->script() ?>
    <?php $this->css() ?>

    <style type="text/css">
    a{
        color:#333;
        text-decoration: none;
    }
    body{
        font-family: "Segoe UI",Helvetica, Arial, 'lucida grande' ,tahoma,verdana,arial,sans-serif;
    }
    a:hover{
        color:red;
    }
    .language{
        margin-right: 10px;
    }
    .language li{
        list-style: none;
        padding: 5px;
        display: block;
    }
    .language li a:hover{
        text-decoration: underline;
    }
    .language li.active{
        text-decoration: none;
    }
    .language li.active span:before{
        content: "[";
    }
    .language li.active span:after{
        content: "]";
    }
    .language li img{
        display: block;
        float:left;
        margin-right: 5px;
        margin-top: 4px;
    }
    .clearfix{
        zoom:1;
    }
    .clearfix:after{
        clear: both;
        content: ".";
        display: block;
        height: 0;
        line-height: 0;
        visibility: hidden;
    }
    .nav{
        background-color: #000;
        position: fixed;
        top:0px;
        left: 0px;
        width: 100%;
        padding:5px;
        color:white;
        border-bottom: 1px solid #133783;
        -webkit-box-shadow: 0px 0px 1px #000;
        -moz-box-shadow: 0px 0px 1px #000;
        box-shadow: 0px 0px 1px #000;
    }
    .left{
        float: left;
    }
    .right{
        float: right;
    }
    .wrapper{
        padding:10px;
    }
    .content{
        width: 100%;
        margin: 50px auto;
    }
    .mobile{
        display: none;
        margin-right: 15px;
        margin-top: 5px;
    }
    .mobile img{
        width: 10px;
        height: 10px;
        padding:5px;
        border: 1px solid #666;
        border-radius: 15px;
    }
    .hide{
        display: none;
        border-bottom:1px solid #ccc;
        padding-bottom: 15px;
        box-shadow: 0 3px 0 #000;
    }
    .show{
        margin-right: 10px;
        margin-top: 3px;
    }
    .menu li.active a{
        color:blue;
    }
    form table{
        width: 100% !important;
    }
</style>
</head>
<body class="<?php echo $this->layout->lang ?>">
    <div class="nav">
        <div class="left" style="margin:0px 0px 0px 10px;font-size:20px">
            <a style="color:white" href="<?php echo $this->baseUrl() ?>">FRAMEWORK</a>
        </div>
        <div class="right mobile">
           <a href="<?php echo $this->current_url(); ?>?mobile=false" title="display in dektop"><img src="<?php echo $this->asset() ?>images/desktop.png" /></a>
        </div>

        <div class="right show">
           <a href=""><img width="25" height="25" src="<?php echo $this->asset() ?>images/icon_cate.png" /></a>
        </div>
       
        
    </div>
    <div class="content">
         <div class="menu clearfix hide">
         
        <div class="left" style="width:150px">
        <?php 
            echo "<li><a href='".$this->baseUrl()."'>".$this->module('application')->loadLanguage('menu')->item1."</a></li>";
            echo "<li><a href='".$this->baseUrl('news')."'>".$this->module('application')->loadLanguage('menu')->item2."</a></li>";
            echo "<li><a href='".$this->baseUrl('register')."'>".$this->module('application')->loadLanguage('menu')->item4."</a></li>";
            echo "<li><a href='".$this->baseUrl('login')."'>".$this->module('application')->loadLanguage('menu')->item5."</a></li>";
            echo "<li><a href='".$this->baseUrl('acp.html')."'>Admin</a></li>";
         ?>
         </div>
          <div class="language clearfix left" style="width:130px;text-align:left">
            <li><?php echo $this->module('application')->loadLanguage('show')->select_lang; ?>:</li>
            <?php 
                $this->module('application')->loadLanguage('list_lang')->show(true);
            ?>
        </div>
        </div>
            <div class="wrapper">
            <h1>Module Mobile</h1>
                <?php $this->content() ?>
           </div>
        <hr />
         <h3><?php echo $this->module('application')->loadLanguage('show')->intro; ?></h3>
         <p>
            <?php echo $this->module('application')->loadLanguage('show')->intro_text; ?>
         </p>
    </div>

    <script type="text/javascript">
    $(document).ready(function(){
        resize();
        $(window).resize(function(){
            resize();
        });

        $(".show a").click(function(){
            $(".hide").slideToggle();
            return false;
        });
    }); 
    function resize(){
        var winwidth=$(window).width();
       if(winwidth>900){
        $(".mobile").show();
       }else{
        $(".mobile").hide();
       }
    }
</script>


</body>
</html>