<!DOCTYPE html>
<html>
<head>
    <noscript>
        <meta http-equiv="refresh" content="0; URL=<?php echo $this->baseUrl('nojavascript') ?>" />
    </noscript>
    <?php $this->title() ?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

   
     <!-- jQuery -->
    <script src="<?php echo $this->asset() ?>js/jquery.js"></script>

    
</head>
<body>
   <h1>Module Admin</h1>
   <?php $this->content() ?>

</body>
</html>